version: "3.9"
services:
  app:
    container_name: aim-tech-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/node-aim
      - /node-aim/node_modules
