version: '3'
services:
   app:
    build: .
    container_name: aim-tech-app
    ports:
      - "3000:3000"

    volumes:
      - . :/node-aim
    
    environment:
      - NODE_ENV=production
